apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: githubrepo.example.com
spec:
  group: example.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                visibility:
                  description: "Repo visibility. It can be 'public' or 'private'"
                  type: string
                  default: "public"
                  enum: ["private", "public"]
              required:
                - visibility
  scope: Namespaced
  names:
    plural: githubrepo
    singular: githubrepo
    kind: GitHubRepo
    shortNames:
    - ghrepo